import { Metadata } from "next";
import Favicon from "/public/images/favicon.ico";

import Navbar from "@/components/Navbar/Navbar";
import Landing from "@/pages/landing";
 export const metadata: Metadata = {
   title: "Jobstack",
   description: "Generated by create next app and chakraUI",
   icons: [{ rel: "icon", url: Favicon.src }],
 };
export default function Home() {

  return (
    <>
      <Navbar />
      <Landing />
    </>
  );
}
